# 1. Install dependencies only when needed
FROM node:16-alpine AS deps
ENV NODE_ENV=development
# Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
RUN apk add --no-cache libc6-compat

WORKDIR /app

# Install dependencies based on the preferred package manager
COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* ./
RUN \
  if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
  elif [ -f package-lock.json ]; then npm ci; \
  elif [ -f pnpm-lock.yaml ]; then yarn global add pnpm && pnpm i; \
  else echo "Lockfile not found." && exit 1; \
  fi

# 2. Rebuild the source code only when needed

COPY . .
# This will do the trick, use the corresponding env file for each environment.
COPY ../../environment/development/.env.development .env.development

EXPOSE 3000

ENV PORT 3000

ENTRYPOINT yarn dev
